FROM ubuntu:22.04 AS builder

#install dependecy
RUN apt-get update && apt-get install -y  \
    dotnet6  \
    git  \
    unzip \
    cmake \
    clang

# setup workdir
WORKDIR /source

# copy sources
ARG VSHARP_FUZZER_ARCHIVE
COPY ${VSHARP_FUZZER_ARCHIVE} .

# unarchive application sources
RUN VSHARP_RUNNER_ARCHIVE_NAME="$(find /source -type f -name '*fuzzer*.zip')" \
	&& unzip ${VSHARP_RUNNER_ARCHIVE_NAME} \
	&& rm ${VSHARP_RUNNER_ARCHIVE_NAME}

# publish fuzzer application
RUN dotnet publish -c Debug -o /app

FROM ubuntu/dotnet-runtime:6.0-22.04_beta

WORKDIR /app
COPY --from=builder /app ./

ENTRYPOINT ["dotnet", "/app/VSharp.Fuzzer.dll"]